name    'syone-rpmdeploy'
version '0.0.1'
source 'syone-rpmdeploy'
author 'Syone'
license 'GPL'
summary 'Garante que RPM está instalado.'
project_page 'N/A'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
# vim:ft=ruby
